version: "2"
exclude_patterns:
  - ".github/"
  - ".travis/"
  - "bin/"
  - "config/"
  - "libs/"
  - "misc/"
  - "scripts/"
  - "**/test/"
  - "**/resources/"
  - "**/examples/"
checks:
  file-lines:
    config:
      threshold: 300
