sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.m2

language: java
jdk:
  - openjdk11

env:
  global:
    - CC_TEST_REPORTER_ID=970bebaf9e240aaf9c86a92251b68f30d373d29f4d07f2e92a0d777009c28a68
    - JACOCO_SOURCE_PATH="interpreter.common interpreter.lacast interpreter.maple interpreter.mathematica interpreter.evaluation"

# install maven 3.6.1
before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.zip
  - unzip -qq apache-maven-3.6.1-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.6.1
  - export PATH=$M2_HOME/bin:$PATH
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - mvn install -DskipTests -B -V -DgenerateJars
  - java -jar bin/lexicon-creator.jar CAS_Maple.csv CAS_Mathematica.csv

script:
  - mvn test -B -DjacocoReport=remote

after_success:
  - bash .travis/fix-jacoco.sh
  - ./cc-test-reporter format-coverage ./target/jacoco-report/jacoco-fix.xml -d --input-type jacoco
  - ./cc-test-reporter upload-coverage -d
#  - export GIT_TAG=lacast-$(date -u "+%m-%d")-r$TRAVIS_BUILD_NUMBER
#  - git config --global user.email "builds@travis-ci.com"
#  - git config --global user.name "Travis CI"
#  - echo -n $GIT_TAG > version
#  - git add version
#  - git commit -m "Set build VERSION number" version
#  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"

#before_deploy:
#  - rm -rf libs/logs
#  - zip -r -9 ${GIT_TAG}.zip bin/* config/* libs/* scripts/* README.md CONTRIBUTING.md

#deploy:
#  provider: releases
#  skip_cleanup: true
#  api_token: $GITHUB_TOKEN
#  file:
#    - ${GIT_TAG}.zip
#  on:
#    tags: true
#    branch: master
