# This configuration defines the path the library and configuration folder for LaCASt.
# You can either specify the location of this file with a flag: "-config=pathToThisConfig.yaml",
# or you put this file into the local directory or your home directory in ".lacast" folder.
lacast.libs.path: "./libs"
lacast.config.path: "./config"

# the cas paths are currently not in use but my be needed later
# any new supported cas must be given in that list
lacast.cas:
  - cas: "Maple"
    paths:
      - "/opt/maple2019"
      - "/opt/maple2019/bin.X86_64_LINUX"
  - cas: "Mathematica"
    paths: "/opt/Wolfram"
  - cas: "SymPy"

# the following settings are optional and are loaded exactly as below
# if nothing is changed because those are the default settings.
lacast.generic:
  elasticsearch.host: "localhost"
  elasticsearch.port: 9200
  elasticsearch.macros.index: "dlmf-macros"
  mathoid.url: "http://localhost:10044/texvcinfo"