# This configuration defines the path the library and configuration folder for LaCASt.
# You can either specify the location of this file with a flag: "-config=pathToThisConfig.yaml",
# or you put this file into the local directory or your home directory in ".lacast" folder.
lacast.libs.path: "./libs"
lacast.config.path: "./config"
lacast.cas.paths:
  - cas: "Maple"
    paths:
      - "/opt/maple2019"
      - "/opt/maple2019/bin.X86_64_LINUX"