# =================================================================================================
# This config contains the general replacement rules TeX inputs
#
# Each rule contains the following information
#   pattern: java regex replacement rule
#   replacement (optional): the replacement string ($1 addresses group 1 of the pattern), no
#                           replacement will delete the match (replace my empty string).
#   groups (optional): when the replacement handles groups, specify the number of groups here
# =================================================================================================
generalReplacements:
  -
    pattern: \\(?:displaystyle|hbox|[Bb]ig[lrg]?|[sb]f)
  -
    # you need single quotes here
    pattern: '[.;<>^/\t\s]+$'
  -
    pattern: (\\hiderel\s*\{\s*([=<>/+\-])\s*})
    replacement: $2
    groups: 2
  -
    pattern: (\d)(?:\s+|\\[;,! ])+(\d)
    replacement: $1$2
    groups: 2
  -
    # replace \* with *
    pattern: \\\*
    replacement: \*