name: translator-build-tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout Repo
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Maven Install
      run: mvn install -DskipTests -B -pl \!interpreter.maple,\!interpreter.mathematica,\!interpreter.core,\!interpreter.roundtrip
    - name: Maven Tests
      run: mvn clean test jacoco:report coveralls:report -pl \!interpreter.maple,\!interpreter.mathematica,\!interpreter.core,\!interpreter.roundtrip
    - name: Coveralls
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}
