name: translator-build-tests

on: [push]

env:
  CC_TEST_REPORTER_ID: 970bebaf9e240aaf9c86a92251b68f30d373d29f4d07f2e92a0d777009c28a68
  JACOCO_SOURCE_PATH: 'interpreter.common interpreter.lacast interpreter.maple interpreter.mathematica interpreter.evaluation'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Repo
        uses: actions/checkout@v1
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Setup Codeclimate Reports
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Maven Install
        run: |
          mvn -Pbuild install -DskipTests -B -V -DgenerateJars
          java -jar bin/lexicon-creator.jar -all
  test:
    runs-on: ubuntu-latest
    needs: [setup, build]
    steps:
      - name: Maven Test
        run: mvn test -B -DjacocoReport=remote
  report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Fix Jacoco Reports
        run: source .travis/fix-jacoco.sh
      - name: Report Report to Codeclimate
        run: |
          ./cc-test-reporter format-coverage ./target/jacoco-report/jacoco-fix.xml --input-type jacoco > jacoco.log 2>&1
          ./cc-test-reporter upload-coverage -d > jacocoUpload.log 2>&1
