name: translator-build-tests
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout Repo
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Maven Build and Test
      run: mvn -B test
    - name: Coveralls
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}
